# Generated by Django 2.1.1 on 2018-11-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
